### ISSUE TITLE
invalid_client on "Connect Accounts"

### ISSUE THREAD

**Issue by AndaHendriksen** [spiir/aiia-sample#134]
From a clean download of the aiia-sample, when I create a user and click "Connect Accounts" I get redirected to: 

`https://api.aiia.eu/v1/oauth/connect?client_id={my_client_id}&response_type=code&redirect_uri=https://localhost:44391/aiia/callback&scope=accounts`

But that gives me an error:
```
400. This is an error, more details below

invalid_client

Client authentication failed, such as if the request contains an invalid client ID or secret.
```

I have changed the following (in both appsettings.json and appsettings.Development.json):
**"ClientId"
"ClientSecret"
"LoginCallbackUrl"
"WebHookSecret"**
To my own values and I can see my client_id in the url when redirected.

Am I missing something?

**Comment by Nahuel-aiiasupport** [comment]
Hello Anda!

Thank you for trying out Aiia!

The best way to get familiar with the capabilities of our API would be to check out our online documentation and use our Postman collection: 

- https://docs.aiia.eu/#/
- https://docs.aiia.eu/#/other/samples

We can offer support on your test/integration efforts through our support channel: support@aiia.eu

Shoot us an e-mail there in case you come across any hurdles with our Postman collection.

Looking forward to hearing from you!

**Comment by jayj** [comment]
Latest master contains a fix for the invalid configuration in `appsettings.Development.json`.
