### ISSUE TITLE
invalid client id 

### ISSUE THREAD

**Issue by paivH** [spiir/aiia-sample#153]
Hi I get this error message when trying to access the account section, "invalid_client

Client authentication failed, such as if the request contains an invalid client ID or secret." I do have client id / secret in my user secrets

What could be the issue? I tested the flow with the same client id /secret with postman and that was successful.

**Comment by ClausFarsinsen** [comment]
Hi, 

Do you mind reaching out to our support team directly at support@aiia.eu? Then we'll do our best to investigate. 

Thank you.

**Comment by paivH** [comment]
Hi! I have actually solved the issue! 
Thanks anyway.

Regards Paiv Darbandi
